export const Fonts = {
  // FONT FAMILY
  FONT_FAMILY_BOLD: '',
  FONT_FAMILY_MEDIUM: '',
  FONT_FAMILY_REGULAR: '',

  // FONT WEIGHT
  FONT_WEIGHT_BOLD: '700',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_REGULAR: '400',
};
